site_name: GwentApp - Dokumentation
docs_dir: pages
nav:
  - Start: start.md
  - Einführung: einfuhrung.md
  - Installation: installation.md
  - API-Dokumentation: api_dokumentation.md
  - Technisches:
    - Randbedingungen: randbedingungen.md
    - Kontext: kontext.md
    - Lösungsstrategie: lösungsstrategie.md
    - Bausteine: baustein.md
    - Laufzeitszenarien: laufzeitszenarien.md
    - Verteilungssicht: verteilungssicht.md
    - Querschnittliche Konzepte: querschnitt.md
    - Architekturentscheidungen: architektur.md
    - Qualitätsanforderungen: qualitätsanforderungen.md
  - Bekannte Probleme/Risiken: probleme_risiken.md
  - ADRs: adr.md
  - Timeline und TODOs: timeline_todos.md
  - Glossar: glossar.md
  - Lizenz: lizenz.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
  icon:
    admonition:
      alert: material/alert-circle
markdown_extensions:
  - toc
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences